### ISSUE TITLE
User authentication problem?

### ISSUE THREAD

**Issue by evz** [datamade/semabot#1]
I'm getting a rather interesting error when I run this app on the server and try to send messages. I've [opened an issue](https://github.com/SpiderOak/flow-python/issues/65) over on the flow-python repo to see if I can get some help.

**Comment by business-cat** [comment]
https://sentry.io/datamade/semaphor-bot/issues/335915502/

**Comment by evz** [comment]
This seems to have been resolved by calling `create_device` with the login info for the bot when initializing the app.
