### ISSUE TITLE
FlowError: Message too long (8670 bytes). Limit is 6000 bytes.

### ISSUE THREAD

**Issue by business-cat** [datamade/semabot#5]
It looks like we need to make sure we are only sending the first 6000 bytes. Or at least make sure that the message we are sending is less than 6000 bytes.

https://sentry.io/datamade/semabot/issues/338625562/

```
FlowError: Message too long (8670 bytes). Limit is 6000 bytes.
(4 additional frame(s) were not displayed)
...
  File "semabot-d-ADH9FP6DO/webhooks.py", line 100, in sentry
    flow.send_message(ORG_ID, channel_id, message)

FlowError: Message too long (8670 bytes). Limit is 6000 bytes.
```

**Comment by evz** [comment]
Should be closed with 9c7f3be39a63273da268772091fb9d6ba2f4d1e2
